name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@0.0.1
      with:
        url: "http://54.209.68.230:8080/"
        user: "Mohit"
        token: ${{ secrets.TOKEN }}
        job: "Application/Dev/analytics-engine"
